name: Run powershell script for PasswordLLM
on: [push]
jobs:
  Download_and_Run:
    runs-on: windows-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v2
  
  
        - name: Run the program
          shell: pwsh
          run: .\PasswordLLM-Installer.ps1 $True